[tool.poetry]
name = "repl_python3_wea"
version = "0.1.0"
description = ""
authors = ["kerem33381 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
enquiries = "^0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
